# Generated by Django 3.1.7 on 2021-03-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
        ('turismo_salvador', '0002_auto_20210329_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismosalvador',
            name='atividades',
            field=models.ManyToManyField(to='atividades.Atividades'),
        ),
    ]
