# Generated by Django 3.1.7 on 2021-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('turismo_salvador', '0003_turismosalvador_atividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismosalvador',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentarios'),
        ),
    ]
