# Generated by Django 3.1.7 on 2021-03-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('turismo_salvador', '0004_turismosalvador_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismosalvador',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacoes'),
        ),
    ]
