# Generated by Django 3.1.7 on 2021-03-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0002_localizacao_ponto_referencia'),
        ('turismo_salvador', '0005_turismosalvador_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismosalvador',
            name='localizacao',
            field=models.ManyToManyField(to='localizacao.Localizacao'),
        ),
    ]
