# Generated by Django 3.1.7 on 2021-03-30 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0002_localizacao_ponto_referencia'),
        ('turismo_salvador', '0006_turismosalvador_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turismosalvador',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='turismosalvador',
            name='localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacao.localizacao'),
            preserve_default=False,
        ),
    ]
