# Generated by Django 3.1.7 on 2021-04-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0005_auto_20210401_1558'),
        ('turismo_salvador', '0010_auto_20210330_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turismosalvador',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacao.localizacao'),
        ),
    ]
