# Generated by Django 3.1.7 on 2021-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('descricao', models.TextField(default='')),
                ('horario_funcionamento', models.TextField(default='')),
                ('idade', models.IntegerField(default='')),
            ],
        ),
    ]
