# Generated by Django 3.1.7 on 2021-03-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.IntegerField(null=True)),
                ('bairro', models.CharField(max_length=100)),
            ],
        ),
    ]
