# Generated by Django 3.1.7 on 2021-03-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0002_localizacao_ponto_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
